-- Authentication user table for the demo application.
-- Lives in the academico schema, matching the JPA mapping of the
-- Usuario entity (com.example.demo.auth). No seed rows: users are
-- created through POST /api/auth/register.
CREATE TABLE IF NOT EXISTS academico.usuario (
    usuario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    state VARCHAR(9) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT usuario_state_check CHECK (state IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);