CREATE TABLE IF NOT EXISTS academico.carrera (
    carrera_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    state VARCHAR(9) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT carrera_state_check CHECK (state IN ('ACTIVO', 'INACTIVO', 'ELIMINADO'))
);

INSERT INTO academico.carrera (nombre) VALUES
    ('Ingeniería en Sistemas'),
    ('Ingeniería Civil'),
    ('Ingeniería Industrial'),
    ('Ingeniería Mecánica'),
    ('Ingeniería Electrónica'),
    ('Arquitectura'),
    ('Administración de Empresas'),
    ('Contaduría Pública y Auditoría'),
    ('Derecho'),
    ('Psicología')
ON CONFLICT (nombre) DO NOTHING;
