CREATE SCHEMA IF NOT EXISTS academico;

CREATE TABLE IF NOT EXISTS academico.curso (
    curso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrera_id INTEGER NOT NULL REFERENCES academico.carrera(carrera_id),
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    state VARCHAR(9) NOT NULL DEFAULT 'ACTIVO',
    CHECK (state IN ('ACTIVO', 'INACTIVO', 'ELIMINADO'))
);

CREATE TABLE IF NOT EXISTS academico.estudiante_curso (
    estudiante_curso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES academico.estudiante(estudiante_id),
    curso_id INTEGER NOT NULL REFERENCES academico.curso(curso_id),
    state VARCHAR(9) NOT NULL DEFAULT 'ACTIVO',
    asignado_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (estudiante_id, curso_id),
    CHECK (state IN ('ACTIVO', 'INACTIVO', 'ELIMINADO'))
);

INSERT INTO academico.curso (carrera_id, codigo, nombre)
SELECT carrera.carrera_id, cursos.codigo, cursos.nombre
FROM (
    VALUES
        ('Ingeniería en Sistemas', 'IS-101', 'Fundamentos de Programación'),
        ('Ingeniería en Sistemas', 'IS-201', 'Bases de Datos'),
        ('Ingeniería en Sistemas', 'IS-301', 'Ingeniería de Software'),
        ('Ingeniería Civil', 'CIV-101', 'Estática'),
        ('Ingeniería Civil', 'CIV-201', 'Resistencia de Materiales'),
        ('Ingeniería Civil', 'CIV-301', 'Diseño Estructural'),
        ('Ingeniería Industrial', 'IND-101', 'Procesos Industriales'),
        ('Ingeniería Industrial', 'IND-201', 'Investigación de Operaciones'),
        ('Ingeniería Industrial', 'IND-301', 'Gestión de Calidad'),
        ('Ingeniería Mecánica', 'MEC-101', 'Mecánica Clásica'),
        ('Ingeniería Mecánica', 'MEC-201', 'Termodinámica'),
        ('Ingeniería Mecánica', 'MEC-301', 'Diseño Mecánico'),
        ('Ingeniería Electrónica', 'ELE-101', 'Circuitos Eléctricos'),
        ('Ingeniería Electrónica', 'ELE-201', 'Electrónica Digital'),
        ('Ingeniería Electrónica', 'ELE-301', 'Microcontroladores'),
        ('Arquitectura', 'ARQ-101', 'Dibujo Arquitectónico'),
        ('Arquitectura', 'ARQ-201', 'Historia de la Arquitectura'),
        ('Arquitectura', 'ARQ-301', 'Diseño Arquitectónico'),
        ('Administración de Empresas', 'ADM-101', 'Administración General'),
        ('Administración de Empresas', 'ADM-201', 'Mercadotecnia'),
        ('Administración de Empresas', 'ADM-301', 'Gestión Financiera'),
        ('Contaduría Pública y Auditoría', 'CPA-101', 'Contabilidad Financiera'),
        ('Contaduría Pública y Auditoría', 'CPA-201', 'Auditoría'),
        ('Contaduría Pública y Auditoría', 'CPA-301', 'Tributación'),
        ('Derecho', 'DER-101', 'Teoría del Derecho'),
        ('Derecho', 'DER-201', 'Derecho Constitucional'),
        ('Derecho', 'DER-301', 'Derecho Civil'),
        ('Psicología', 'PSI-101', 'Psicología General'),
        ('Psicología', 'PSI-201', 'Psicología Social'),
        ('Psicología', 'PSI-301', 'Evaluación Psicológica')
) AS cursos(carrera_nombre, codigo, nombre)
JOIN academico.carrera carrera ON carrera.nombre = cursos.carrera_nombre
ON CONFLICT DO NOTHING;

-- Optional verification queries. Uncomment only when you want to inspect the result.
-- SELECT carrera.nombre, COUNT(curso.curso_id) AS cursos
-- FROM academico.carrera carrera
-- LEFT JOIN academico.curso curso ON curso.carrera_id = carrera.carrera_id
-- GROUP BY carrera.carrera_id, carrera.nombre
-- ORDER BY carrera.nombre;

-- SELECT curso.curso_id, carrera.nombre AS carrera, curso.codigo, curso.nombre, curso.state
-- FROM academico.curso curso
-- JOIN academico.carrera carrera ON carrera.carrera_id = curso.carrera_id
-- ORDER BY carrera.nombre, curso.nombre;
